printWidth: 120
tabWidth: 4
trailingComma: 'all'
semi: true
singleQuote: true
arrowParens: 'always'
overrides:
  - files: '*.css'
    options:
      tabWidth: 2
  - files: '*.yaml'
    options:
      tabWidth: 2
  - files: '*.yml'
    options:
      tabWidth: 2
  - files: '*.json'
    options:
      tabWidth: 2
